apiVersion: apps/v1
kind: Deployment
metadata:
  name: tendorix-backend
  namespace: tendorix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tendorix-backend
  template:
    metadata:
      labels:
        app: tendorix-backend
    spec:
      containers:
      - name: backend
        image: tendorix/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: mongo-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: secret-key
        - name: AZURE_DOC_INTEL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: azure-doc-intel-endpoint
        - name: AZURE_DOC_INTEL_KEY
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: azure-doc-intel-key
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: gemini-api-key
        - name: HF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: tendorix-secrets
              key: hf-api-token
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tendorix-backend-service
  namespace: tendorix
spec:
  selector:
    app: tendorix-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP